name: Vue 3 CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to server
        env:
          SERVER: ${{ secrets.SERVER }}
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          # Deploying files to the server
          sshpass -p "$PASSWORD" scp -o StrictHostKeyChecking=no -r ./dist $USER@$SERVER:Nammotors-frontend/dist
          sshpass -p "$PASSWORD" scp -o StrictHostKeyChecking=no ./server.js $USER@$SERVER:Nammotors-frontend/

          # SSH into the server and perform deployment tasks
          sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no $USER@$SERVER << 'EOF'
            # Navigate to deployment directory
            cd Nammotors-frontend

            # Install Node.js dependencies (if necessary)
            npm install

            # Start the server using PM2
            pm2 start server.js --name vue-app

            # Ensure PM2 is running after deployment
            pm2 save
          EOF
